services:
  web:
    container_name: miniktv
    image: 127.0.0.1:5000/miniktv/miniktv:latest
    ports:
      - "8080:80"
    volumes:
      - ./db:/usr/share/nginx/html/db:ro
      - ./src/config:/usr/share/nginx/html/config:ro
    environment:
      - TZ=Asia/Taipei
    restart: unless-stopped
